# Generated by Django 2.2 on 2019-09-04 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller1', '0001_initial'),
        ('advisor', '0001_initial'),
        ('user_seller', '0001_initial'),
        ('investor', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('notif_type', models.CharField(max_length=255)),
                ('notif_statement', models.CharField(max_length=255)),
                ('notif_on', models.CharField(blank=True, max_length=255, null=True)),
                ('notif_on_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notif_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.FileField(blank=True, default='files/advisor-img2.png', null=True, upload_to='files/')),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('region', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lngt', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('address_line', models.CharField(max_length=255)),
                ('about_me', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.BooleanField(default=False)),
                ('social', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('trial', models.BooleanField(default=True)),
                ('otp', models.CharField(blank=True, max_length=255, null=True)),
                ('advise_type', models.ManyToManyField(blank=True, related_name='profile_from_advisor', to='advisor.Advisor')),
                ('curr_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Chat')),
                ('invest_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_from_investor', to='investor.Investor')),
                ('investors_type', models.ManyToManyField(blank=True, related_name='related_investor', to='investor.Investor')),
                ('just_advise', models.ManyToManyField(blank=True, related_name='profile_from_jadvisor', to='advisor.Advisor')),
                ('just_invest', models.ManyToManyField(blank=True, related_name='profile_from_jinvestor', to='investor.Investor')),
                ('just_sell', models.ManyToManyField(blank=True, related_name='profile_from_jseller', to='seller1.Seller1')),
                ('notifs', models.ManyToManyField(blank=True, null=True, to='profiles.Notification')),
                ('sell_type', models.ManyToManyField(blank=True, related_name='profile_from_seller', to='seller1.Seller1')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_advise', models.ManyToManyField(blank=True, to='user_seller.Advise')),
                ('user_invest', models.ManyToManyField(blank=True, to='user_seller.Invest')),
                ('user_sell', models.ManyToManyField(blank=True, to='user_seller.Sell')),
            ],
        ),
    ]
