# Generated by Django 2.2.3 on 2019-09-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_investor_usd_askprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinvestor',
            name='investment_bracket_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualinvestor',
            name='investment_bracket_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinvestor',
            name='capital_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companyinvestor',
            name='investment_bracket',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualinvestor',
            name='capital_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='individualinvestor',
            name='investment_bracket',
            field=models.CharField(max_length=255),
        ),
    ]
