# Generated by Django 2.2.3 on 2019-10-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_remove_investor_usd_askprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinvestor',
            name='investment_bracket_usd',
        ),
        migrations.RemoveField(
            model_name='individualinvestor',
            name='investment_bracket_usd',
        ),
        migrations.AddField(
            model_name='companyinvestor',
            name='investment_max_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='companyinvestor',
            name='investment_min_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='individualinvestor',
            name='investment_max_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='individualinvestor',
            name='investment_min_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
    ]
