# Generated by Django 2.2 on 2019-09-04 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ablumfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller1',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('country_code_primary', models.CharField(default='+91', max_length=255)),
                ('phone_number_primary', models.CharField(max_length=15)),
                ('email_adress', models.EmailField(max_length=40)),
                ('about_seller', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('completed', models.IntegerField(default=0)),
                ('category1', models.CharField(blank=True, max_length=255)),
                ('category2', models.CharField(blank=True, max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(default='', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('region', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('adress', models.TextField(blank=True, max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lngt', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('address_line', models.CharField(max_length=255)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('album_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('viewers', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_type', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_info', models.TextField()),
                ('exp_ret', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('seller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller1.Seller1')),
            ],
        ),
        migrations.CreateModel(
            name='SellStartup',
            fields=[
                ('startup_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField()),
                ('sought_equity', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('asking_price', models.IntegerField()),
                ('revenue_growth', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('year_established', models.IntegerField()),
                ('reason_selling', models.TextField()),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('seller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller1.Seller1')),
            ],
        ),
        migrations.CreateModel(
            name='SellIpcode',
            fields=[
                ('ipcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('startup_type', models.CharField(blank=True, max_length=255)),
                ('research_title', models.TextField()),
                ('about', models.TextField()),
                ('asking_price', models.IntegerField()),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('seller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller1.Seller1')),
            ],
        ),
        migrations.CreateModel(
            name='SellFranchise',
            fields=[
                ('franchise_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('num_outlets', models.IntegerField(default=1, max_length=100)),
                ('franchise_type', models.CharField(blank=True, max_length=255)),
                ('prod_info', models.TextField()),
                ('looking_for', models.TextField()),
                ('asking_price', models.IntegerField(blank=True, default=0, null=True)),
                ('cap_req', models.IntegerField(blank=True, default=0, null=True)),
                ('exp_ret', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('seller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller1.Seller1')),
            ],
        ),
        migrations.CreateModel(
            name='SellEquity',
            fields=[
                ('equity_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('about_business', models.TextField(blank=True, max_length=255)),
                ('stake', models.DecimalField(blank=True, decimal_places=20, max_digits=30)),
                ('asking_price', models.IntegerField(blank=True)),
                ('year', models.IntegerField(blank=True)),
                ('reason', models.TextField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('seller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller1.Seller1')),
            ],
        ),
        migrations.CreateModel(
            name='SellBusiness',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField()),
                ('asking_price', models.IntegerField()),
                ('year_established', models.IntegerField()),
                ('reason_selling', models.TextField()),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('seller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller1.Seller1')),
            ],
        ),
        migrations.CreateModel(
            name='SellAsset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=255)),
                ('about_asset', models.TextField(blank=True, max_length=255)),
                ('asking_price', models.IntegerField(blank=True)),
                ('purchase_price', models.IntegerField(blank=True)),
                ('purchase_year', models.IntegerField(blank=True)),
                ('reason_selling', models.TextField(blank=True, max_length=255)),
                ('seller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller1.Seller1')),
            ],
        ),
        migrations.CreateModel(
            name='SellApp',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField()),
                ('startup_type', models.CharField(blank=True, max_length=255)),
                ('email_app', models.EmailField(blank=True, default='nothing@gmail.com', max_length=255)),
                ('asking_price', models.IntegerField()),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('monitization_method', models.CharField(blank=True, max_length=255)),
                ('average_monthly_revenue', models.IntegerField()),
                ('average_monthly_expense', models.IntegerField()),
                ('date_established', models.DateField()),
                ('average_monthly_downloads', models.IntegerField()),
                ('platform_used', models.CharField(blank=True, max_length=500)),
                ('y1_views', models.IntegerField(blank=True, default=0, null=True)),
                ('y2_views', models.IntegerField(blank=True, default=0, null=True)),
                ('y3_views', models.IntegerField(blank=True, default=0, null=True)),
                ('y1_users', models.IntegerField(blank=True, default=0, null=True)),
                ('y2_users', models.IntegerField(blank=True, default=0, null=True)),
                ('y3_users', models.IntegerField(blank=True, default=0, null=True)),
                ('seller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller1.Seller1')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueModel',
            fields=[
                ('revenue_id', models.AutoField(primary_key=True, serialize=False)),
                ('rev_year', models.IntegerField()),
                ('year_16', models.IntegerField(blank=True, default=0)),
                ('year_15', models.IntegerField(blank=True, default=0)),
                ('year_14', models.IntegerField(blank=True, default=0)),
                ('year_13', models.IntegerField(blank=True, default=0)),
                ('year_17', models.IntegerField(blank=True, default=0)),
                ('no_emp', models.IntegerField(blank=True, default=0)),
                ('cp_emp', models.IntegerField(blank=True, default=0)),
                ('seller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller1.Seller1')),
            ],
        ),
        migrations.CreateModel(
            name='RaiseLoan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('about_business', models.TextField(blank=True, max_length=255)),
                ('loan_amount', models.IntegerField(blank=True)),
                ('sought_interest', models.DecimalField(blank=True, decimal_places=20, max_digits=30)),
                ('year_established', models.IntegerField(blank=True)),
                ('reason_loan', models.TextField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('seller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller1.Seller1')),
            ],
        ),
    ]
