# Generated by Django 2.2 on 2019-09-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellipcode',
            name='product_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
