# Generated by Django 2.2 on 2019-09-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller1', '0002_sellipcode_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellipcode',
            name='asking_price',
            field=models.BigIntegerField(),
        ),
    ]
