# Generated by Django 2.2 on 2019-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller1', '0003_auto_20190905_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller1',
            name='usd_askprice',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
