# Generated by Django 2.2 on 2019-09-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller1', '0004_seller1_usd_askprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller1',
            name='usd_askprice',
        ),
    ]
