# Generated by Django 2.2.3 on 2019-09-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller1', '0005_remove_seller1_usd_askprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseloan',
            name='loan_amount_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenuemodel',
            name='cp_emp_usd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='revenuemodel',
            name='rev_year_usd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='revenuemodel',
            name='year_13_usd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='revenuemodel',
            name='year_14_usd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='revenuemodel',
            name='year_15_usd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='revenuemodel',
            name='year_16_usd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='revenuemodel',
            name='year_17_usd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sellapp',
            name='asking_price_usd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sellapp',
            name='average_monthly_expense_usd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sellapp',
            name='average_monthly_revenue_usd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sellasset',
            name='asking_price_usd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sellasset',
            name='purchase_price_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellbusiness',
            name='asking_price_usd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sellequity',
            name='asking_price_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellfranchise',
            name='asking_price_usd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sellipcode',
            name='asking_price_usd',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sellstartup',
            name='asking_price_usd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='raiseloan',
            name='loan_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
