# Generated by Django 2.2.3 on 2019-09-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller1', '0007_auto_20190922_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellbusiness',
            name='asking_price_usd',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
