# Generated by Django 2.2.3 on 2019-09-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller1', '0008_auto_20190922_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuemodel',
            name='cp_emp_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenuemodel',
            name='year_13_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenuemodel',
            name='year_14_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenuemodel',
            name='year_15_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenuemodel',
            name='year_16_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenuemodel',
            name='year_17_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
