# Generated by Django 2.2.3 on 2019-09-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller1', '0009_auto_20190922_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellbusiness',
            name='asking_price_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
    ]
