# Generated by Django 2.2.3 on 2019-10-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller1', '0011_auto_20190922_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellfranchise',
            name='cap_req_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
    ]
