# Generated by Django 2.2 on 2019-09-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='iso',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
