# Generated by Django 2.2 on 2019-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='files/')),
                ('name', models.CharField(blank=True, default=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KAlbumForFile',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('files', models.ManyToManyField(blank=True, null=True, to='album.File')),
                ('seller', models.ManyToManyField(blank=True, null=True, to='seller1.SellBusiness')),
            ],
        ),
    ]
