# Generated by Django 2.2.3 on 2019-09-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_advisor_usd_askprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessadvisor',
            name='hour_fee_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupadvisor',
            name='hour_fee_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
