# Generated by Django 2.2.3 on 2019-09-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_auto_20190922_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='usd_askprice',
        ),
    ]
