from django.urls import path, re_path
from . import views
from django.conf.urls import url
from django.urls import path
from seller1.sms import otp_message, email_message, email_forgot, forgot_password

urlpatterns = [
    url('ajax/otp/', otp_message, name='otp-message'),
    url('ajax/email/', email_message, name='email-message'),
    url('add_viewer/', views.add_viewer, name='add-viewer'),
    url('check-email/', email_forgot, name='check-email'),
    url('save_view/', views.save_view, name='save-view'),
    url('forgot-password/', forgot_password, name='forgot-password'),
    path('bcard/<business_id>', views.seller_render_to_pdf, name='seller-image'),
    url('ajax/update/files/', views.UpdateFiles, name='business-update-files'),
    url('ajax/validate/rev/', views.validate_rev, name='business-validate-rev'),
    url('ajax/validate/bsn/', views.validate_bsn, name='business-validate-bsn'),
    url('ajax/validate/asset/', views.validate_asset, name='business-validate-asset'),
    url('ajax/validate/equity/', views.validate_equity, name='business-validate-equity'),
    url('ajax/validate/loan/', views.validate_loan, name='business-validate-loan'),
    url('ajax/validate/startup/', views.validate_startup, name='business-validate-startup'),
    url('ajax/validate/app/', views.validate_app, name='business-validate-app'),
    url('ajax/validate/ipcode/', views.validate_ipcode, name='business-validate-ipcode'),
    url('ajax/validate/franchise/', views.validate_franchise, name='business-validate-franchise'),
    url('ajax/validate/supplier/', views.validate_supplier, name='business-validate-supplier'),
    path('delete/<business_id>', views.SellBusinessDelete, name='business-delete'),
    path('asset/delete/<business_id>', views.SellAssetDelete, name='asset-delete'),
    path('app/delete/<business_id>', views.SellAppDelete, name='app-delete'),
    path('loan/delete/<business_id>', views.RaiseLoanDelete, name='loan-delete'),
    path('equity/delete/<business_id>', views.SellEquityDelete, name='equity-delete'),
    path('ipcode/delete/<business_id>', views.SellIpcodeDelete, name='ipcode-delete'),
    path('franchise/delete/<business_id>', views.SellFranchiseDelete, name='franchise-delete'),
    path('startup/delete/<business_id>', views.SellStartupDelete, name='startup-delete'),
    path('supplier/delete/<business_id>', views.SellSupplierDelete, name='supplier-delete'),
    url('ajax/validate/$', views.validate, name='business-validate'),
    re_path(r'^$', views.seller, name='seller'),
    path('asset', views.seller_asset, name='asset'),
    path('equity', views.seller_equity, name='equity'),
    path('loan', views.seller_loan, name='loan'),
    path('startup', views.seller_startup, name='startup'),
    path('app', views.seller_app, name='app'),
    path('ipcode', views.seller_ipcode, name='ipcode'),
    path('franchise', views.seller_franchise, name='franchise'),
    path('supplier', views.seller_supplier, name='supplier'),
    path('seller_update/<business_id>', views.SellerUpdate, name='business-update'),
    path('asset_update/<business_id>', views.AssetUpdate, name='asset-update'),
    path('equity_update/<business_id>', views.EquityUpdate, name='equity-update'),
    path('loan_update/<business_id>', views.LoanUpdate, name='loan-update'),
    path('startup_update/<business_id>', views.StartupUpdate, name='startup-update'),
    path('app_update/<business_id>', views.AppUpdate, name='app-update'),
    path('ipcode_update/<business_id>', views.IpcodeUpdate, name='ipcode-update'),
    path('franchise_update/<business_id>', views.FranchiseUpdate, name='franchise-update'),
    path('supplier_update/<business_id>', views.SupplierUpdate, name='supplier-update'),
    path('seller_detail/<business_id>', views.BusinessDetail, name='business-detail'),
    path('user_detail/<business_id>', views.detail_sell_type, name='seller-user-detail'),
    path('all_detail/<business_id>', views.just_sell_type, name='seller-all-detail'),
    path('display/business', views.display_busi, name='seller-display-busi'),
    path('display/web', views.display_web, name='seller-display-web'),
    path('display/startup', views.display_startup, name='seller-display-startup'),
    path('display/franchise', views.display_franchise, name='seller-display-franchise'),
    path('display/supplier', views.display_supplier, name='seller-display-supplier'),
    path('display/advisors', views.display_advise, name='seller-display-advisors'),
    path('display/advisors_startup', views.display_advise_startup, name='seller-display-advisors_startup'),
    path('display/investors', views.display_invest, name='seller-display-investors'),
    path('get_sellers/business', views.show_sellers, name='get_sellers'),
    path('get_advisors/business', views.show_advisors, name='get_advisors'),
    path('get_advisors_startup/business', views.show_advisors_startup, name='get_advisors_startup'),
    path('get_investors/business', views.show_investors, name='get_investors'),
    path('just_add', views.just_add_cart, name='just_add'),
    path('just_remove', views.just_remove_cart, name='just_remove'),
    path('add_seller_cart', views.add_sell_cart, name='add_sell_cart'),
    path('remove_seller_cart', views.remove_sell_cart, name='remove_sell_cart'),
    path('add_investor_cart', views.add_invest_cart, name='add_invest_cart'),
    path('remove_investor_cart', views.remove_invest_cart, name='remove_invest_cart'),
    path('add_advisor_cart', views.add_advise_cart, name='add_advise_cart'),
    path('remove_advisor_cart', views.remove_advise_cart, name='remove_advise_cart'),
    path('fetch-detail/<business_id>', views.fetch_detail_id, name='fetch-sell-id'),
    path('fetch-sell/<business_id>', views.fetch_sell_id, name='fetch-sell-id'),
    path('fetch-advise/<business_id>', views.fetch_advise_id, name='fetch-sell-id'),
    path('fetch-invest/<business_id>', views.fetch_invest_id, name='fetch-sell-id'),

    url('get_model_fields/', views.getModelfields, name='business-model_fields'),
]
